server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
      name: config
  cloud:
      config:
        server:
          git:
            uri: https://github.com/moneyice/StockAnalyzer/     # 配置git仓库的地址
            search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
            username:                                             # git仓库的账号
            password:                                             # git仓库的密码